@baseUrl = http://localhost:80/api

##Rotas Protegidas (somente o proprio usuario ou o admin podem utiliza-las)

### LISTAR (caso seja um admin logado consegue ver todos, se nao ve somente os proprios)
GET {{baseUrl}}/relatorios
Content-Type: application/json
Authorization: Bearer COLE_SEU_TOKEN_AQUI

### EXPORTAR PARA CSV (Exporta relatórios listados para CSV)
GET {{baseUrl}}/relatorios?format=csv
Authorization: Bearer COLE_SEU_TOKEN_AQUI

### BUSCAR POR ID somente admin e dono da task podem ver
GET {{baseUrl}}/relatorios/2
Content-Type: application/json
Authorization: Bearer COLE_SEU_TOKEN_AQUI

### LISTAR COM FILTRO
GET {{baseUrl}}/relatorios?cliente=Escola%20Y
Content-Type: application/json
Authorization: Bearer COLE_SEU_TOKEN_AQUI

### CRIAR UM RELATÓRIO (POST)
# Teste de sucesso
POST {{baseUrl}}/relatorios
Content-Type: application/json
Authorization: Bearer COLE_SEU_TOKEN_AQUI

{
    "titulo": "Formatação de Notebook",
    "cliente": "João da Silva",
    "data_realizacao": "2023-11-21",
    "valor": 150.00,
    "descricao": "Notebook Dell estava lento. Formatado com Windows 11."
}

### TESTAR VALIDAÇÃO (POST com Erro)
# Deve retornar erro 400 pois valor eh negativo
POST {{baseUrl}}/relatorios
Content-Type: application/json
Authorization: Bearer COLE_SEU_TOKEN_AQUI

{
    "usuario_id": 1,
    "titulo": "Teste Erro",
    "cliente": "Errado",
    "data_realizacao": "2023-11-21",
    "valor": -50.00
}

### ATUALIZAR por ID(PUT) somente dono da task e admin podem atualizar
PUT {{baseUrl}}/relatorios/2
Content-Type: application/json
Authorization: Bearer COLE_SEU_TOKEN_AQUI

{
    "titulo": "Formatação de Notebook (Urgente)",
    "cliente": "João da Silva",
    "data_realizacao": "2023-11-21",
    "valor": 200.00,
    "descricao": "Adicionado taxa de urgência."
}

### DELETAR por ID (DELETE)
DELETE {{baseUrl}}/relatorios/1
Content-Type: application/json
Authorization: Bearer COLE_SEU_TOKEN_AQUI